name: Deploy to Server # The name of this workflow, shown in the Actions tab.

on:
  push:
    branches:
      - main # Trigger the workflow only when changes are pushed to the main branch.

jobs: # Define one or more jobs (here, we have one: 'deploy').
  deploy:
    runs-on: ubuntu-latest # GitHub will use an Ubuntu VM to execute this job.

    steps: # Steps define the tasks for this job.
      - name: Checkout Code
        uses: actions/checkout@v3
        # This action checks out your repository code into the VM.

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.23.4"
        # This sets up a Go environment on the VM, using the specified version.

      - name: Build the Project
        run: |
          go build -o webserver main.go
        # This compiles your Go project into a binary called 'webserver'.

      - name: Deploy to Server
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.SERVER_IP }} # Your server's IP, stored as a GitHub secret.
          username: root # The SSH username
          key: ${{ secrets.SSH_PRIVATE_KEY }} # The private SSH key, stored as a GitHub secret.
          port: 22 # Default SSH port.
          script: |
            sudo systemctl stop webserver
            rm -rf /var/www/webserver/*
            scp webserver user@your_server_ip:/var/www/webserver/
            sudo systemctl start webserver
        # This step connects to your server via SSH and deploys the binary.
