name: Deploy to VPS

on:
  push:
    branches:
      - main # Trigger on push to main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout Code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Set Up Go Environment
      - name: Set Up Go
        uses: actions/setup-go@v3
        with:
          go-version: "1.23.3"

      # Step 3: Verify Dependencies
      - name: Install Dependencies
        run: |
          go mod tidy
          go mod download

      # Step 4: Debugging Step - List Files
      - name: Debug - List Files
        run: ls -R

      # Step 5: Build the Go Application
      - name: Build Application
        run: |
          go build -o app main.go

      # Step 6: Deploy to VPS via SCP
      - name: Deploy to VPS
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.SERVER_IP }}
          username: root
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "app"
          target: "/root/app"

      # Step 7: Restart the Server
      - name: Restart Server
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SERVER_IP }}
          username: root
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            sudo systemctl restart my-go-app
